name: uuid_wasm_test
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  uuid: ^4.4.2

dev_dependencies:
  test: ^1.24.0
  rexios_lints: ^8.0.0
